// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/agent/agent.proto

package agent

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	status "github.com/swinslow/peridot-jobrunner/pkg/status"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status1 "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ControllerMsg can consist of one of the available types of
// messages from the main controller to the Agent.
type ControllerMsg struct {
	// Types that are valid to be assigned to Cm:
	//	*ControllerMsg_Start
	//	*ControllerMsg_Status
	Cm                   isControllerMsg_Cm `protobuf_oneof:"cm"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ControllerMsg) Reset()         { *m = ControllerMsg{} }
func (m *ControllerMsg) String() string { return proto.CompactTextString(m) }
func (*ControllerMsg) ProtoMessage()    {}
func (*ControllerMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_a60391ce6a1a9c17, []int{0}
}

func (m *ControllerMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControllerMsg.Unmarshal(m, b)
}
func (m *ControllerMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControllerMsg.Marshal(b, m, deterministic)
}
func (m *ControllerMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControllerMsg.Merge(m, src)
}
func (m *ControllerMsg) XXX_Size() int {
	return xxx_messageInfo_ControllerMsg.Size(m)
}
func (m *ControllerMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ControllerMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ControllerMsg proto.InternalMessageInfo

type isControllerMsg_Cm interface {
	isControllerMsg_Cm()
}

type ControllerMsg_Start struct {
	Start *StartReq `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ControllerMsg_Status struct {
	Status *StatusReq `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

func (*ControllerMsg_Start) isControllerMsg_Cm() {}

func (*ControllerMsg_Status) isControllerMsg_Cm() {}

func (m *ControllerMsg) GetCm() isControllerMsg_Cm {
	if m != nil {
		return m.Cm
	}
	return nil
}

func (m *ControllerMsg) GetStart() *StartReq {
	if x, ok := m.GetCm().(*ControllerMsg_Start); ok {
		return x.Start
	}
	return nil
}

func (m *ControllerMsg) GetStatus() *StatusReq {
	if x, ok := m.GetCm().(*ControllerMsg_Status); ok {
		return x.Status
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ControllerMsg) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ControllerMsg_Start)(nil),
		(*ControllerMsg_Status)(nil),
	}
}

// AgentMsg can consist of one of the available types of messages from the
// Agent to the main controller.
type AgentMsg struct {
	// Types that are valid to be assigned to Am:
	//	*AgentMsg_Status
	Am                   isAgentMsg_Am `protobuf_oneof:"am"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AgentMsg) Reset()         { *m = AgentMsg{} }
func (m *AgentMsg) String() string { return proto.CompactTextString(m) }
func (*AgentMsg) ProtoMessage()    {}
func (*AgentMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_a60391ce6a1a9c17, []int{1}
}

func (m *AgentMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentMsg.Unmarshal(m, b)
}
func (m *AgentMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentMsg.Marshal(b, m, deterministic)
}
func (m *AgentMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentMsg.Merge(m, src)
}
func (m *AgentMsg) XXX_Size() int {
	return xxx_messageInfo_AgentMsg.Size(m)
}
func (m *AgentMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentMsg.DiscardUnknown(m)
}

var xxx_messageInfo_AgentMsg proto.InternalMessageInfo

type isAgentMsg_Am interface {
	isAgentMsg_Am()
}

type AgentMsg_Status struct {
	Status *StatusReport `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

func (*AgentMsg_Status) isAgentMsg_Am() {}

func (m *AgentMsg) GetAm() isAgentMsg_Am {
	if m != nil {
		return m.Am
	}
	return nil
}

func (m *AgentMsg) GetStatus() *StatusReport {
	if x, ok := m.GetAm().(*AgentMsg_Status); ok {
		return x.Status
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AgentMsg) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AgentMsg_Status)(nil),
	}
}

// JobConfig defines the configuration for a job.
// Relevance of configuration details will depend upon the Agent's
// capabilities.
type JobConfig struct {
	CodeInputs []*JobConfig_CodeInput `protobuf:"bytes,1,rep,name=codeInputs,proto3" json:"codeInputs,omitempty"`
	// codewriter: directory where code can be written
	CodeOutputDir string                 `protobuf:"bytes,2,opt,name=codeOutputDir,proto3" json:"codeOutputDir,omitempty"`
	SpdxInputs    []*JobConfig_SpdxInput `protobuf:"bytes,3,rep,name=spdxInputs,proto3" json:"spdxInputs,omitempty"`
	// spdxwriter: directory path to write one or more output SPDX files
	SpdxOutputDir        string             `protobuf:"bytes,4,opt,name=spdxOutputDir,proto3" json:"spdxOutputDir,omitempty"`
	Jkvs                 []*JobConfig_JobKV `protobuf:"bytes,5,rep,name=jkvs,proto3" json:"jkvs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *JobConfig) Reset()         { *m = JobConfig{} }
func (m *JobConfig) String() string { return proto.CompactTextString(m) }
func (*JobConfig) ProtoMessage()    {}
func (*JobConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a60391ce6a1a9c17, []int{2}
}

func (m *JobConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobConfig.Unmarshal(m, b)
}
func (m *JobConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobConfig.Marshal(b, m, deterministic)
}
func (m *JobConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobConfig.Merge(m, src)
}
func (m *JobConfig) XXX_Size() int {
	return xxx_messageInfo_JobConfig.Size(m)
}
func (m *JobConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_JobConfig.DiscardUnknown(m)
}

var xxx_messageInfo_JobConfig proto.InternalMessageInfo

func (m *JobConfig) GetCodeInputs() []*JobConfig_CodeInput {
	if m != nil {
		return m.CodeInputs
	}
	return nil
}

func (m *JobConfig) GetCodeOutputDir() string {
	if m != nil {
		return m.CodeOutputDir
	}
	return ""
}

func (m *JobConfig) GetSpdxInputs() []*JobConfig_SpdxInput {
	if m != nil {
		return m.SpdxInputs
	}
	return nil
}

func (m *JobConfig) GetSpdxOutputDir() string {
	if m != nil {
		return m.SpdxOutputDir
	}
	return ""
}

func (m *JobConfig) GetJkvs() []*JobConfig_JobKV {
	if m != nil {
		return m.Jkvs
	}
	return nil
}

// codereader: code paths under analysis
type JobConfig_CodeInput struct {
	// short description of this code input.
	// "primary" means that it is the primary code under analysis;
	// most codereader agents will expect a "primary" input.
	// otherwise, may be e.g. agent name for the upstream agent that
	// retrieved and placed the code in place.
	// if the Agent is also an spdxreader, then the CodeInput could
	// have a corresponding SpdxInput describing it in further detail.
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// path to directory or file to be analyzed
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobConfig_CodeInput) Reset()         { *m = JobConfig_CodeInput{} }
func (m *JobConfig_CodeInput) String() string { return proto.CompactTextString(m) }
func (*JobConfig_CodeInput) ProtoMessage()    {}
func (*JobConfig_CodeInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_a60391ce6a1a9c17, []int{2, 0}
}

func (m *JobConfig_CodeInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobConfig_CodeInput.Unmarshal(m, b)
}
func (m *JobConfig_CodeInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobConfig_CodeInput.Marshal(b, m, deterministic)
}
func (m *JobConfig_CodeInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobConfig_CodeInput.Merge(m, src)
}
func (m *JobConfig_CodeInput) XXX_Size() int {
	return xxx_messageInfo_JobConfig_CodeInput.Size(m)
}
func (m *JobConfig_CodeInput) XXX_DiscardUnknown() {
	xxx_messageInfo_JobConfig_CodeInput.DiscardUnknown(m)
}

var xxx_messageInfo_JobConfig_CodeInput proto.InternalMessageInfo

func (m *JobConfig_CodeInput) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *JobConfig_CodeInput) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

// spdxreader: paths to multiple earlier SPDX files which may be reused
type JobConfig_SpdxInput struct {
	// short description for source of SPDX file; may be e.g. agent name,
	// "former" for former known good SPDX files; etc.
	// don't try to include too much detail here; the agent can read the
	// SPDX file and get more data if it wants to. this is just meant to
	// give enough info to the agent to decide whether it potentially
	// cares about the file at all.
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// path to SPDX file (or directory containing them) for this source
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobConfig_SpdxInput) Reset()         { *m = JobConfig_SpdxInput{} }
func (m *JobConfig_SpdxInput) String() string { return proto.CompactTextString(m) }
func (*JobConfig_SpdxInput) ProtoMessage()    {}
func (*JobConfig_SpdxInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_a60391ce6a1a9c17, []int{2, 1}
}

func (m *JobConfig_SpdxInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobConfig_SpdxInput.Unmarshal(m, b)
}
func (m *JobConfig_SpdxInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobConfig_SpdxInput.Marshal(b, m, deterministic)
}
func (m *JobConfig_SpdxInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobConfig_SpdxInput.Merge(m, src)
}
func (m *JobConfig_SpdxInput) XXX_Size() int {
	return xxx_messageInfo_JobConfig_SpdxInput.Size(m)
}
func (m *JobConfig_SpdxInput) XXX_DiscardUnknown() {
	xxx_messageInfo_JobConfig_SpdxInput.DiscardUnknown(m)
}

var xxx_messageInfo_JobConfig_SpdxInput proto.InternalMessageInfo

func (m *JobConfig_SpdxInput) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *JobConfig_SpdxInput) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

// job-specific key-value pairs; will vary by agent
type JobConfig_JobKV struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobConfig_JobKV) Reset()         { *m = JobConfig_JobKV{} }
func (m *JobConfig_JobKV) String() string { return proto.CompactTextString(m) }
func (*JobConfig_JobKV) ProtoMessage()    {}
func (*JobConfig_JobKV) Descriptor() ([]byte, []int) {
	return fileDescriptor_a60391ce6a1a9c17, []int{2, 2}
}

func (m *JobConfig_JobKV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobConfig_JobKV.Unmarshal(m, b)
}
func (m *JobConfig_JobKV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobConfig_JobKV.Marshal(b, m, deterministic)
}
func (m *JobConfig_JobKV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobConfig_JobKV.Merge(m, src)
}
func (m *JobConfig_JobKV) XXX_Size() int {
	return xxx_messageInfo_JobConfig_JobKV.Size(m)
}
func (m *JobConfig_JobKV) XXX_DiscardUnknown() {
	xxx_messageInfo_JobConfig_JobKV.DiscardUnknown(m)
}

var xxx_messageInfo_JobConfig_JobKV proto.InternalMessageInfo

func (m *JobConfig_JobKV) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *JobConfig_JobKV) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// StartReq requests that a Job be started on this Agent. An Agent should
// respond to this (eventually) by sending a StatusReport.
type StartReq struct {
	// configuration for this job
	Config               *JobConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *StartReq) Reset()         { *m = StartReq{} }
func (m *StartReq) String() string { return proto.CompactTextString(m) }
func (*StartReq) ProtoMessage()    {}
func (*StartReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a60391ce6a1a9c17, []int{3}
}

func (m *StartReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartReq.Unmarshal(m, b)
}
func (m *StartReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartReq.Marshal(b, m, deterministic)
}
func (m *StartReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartReq.Merge(m, src)
}
func (m *StartReq) XXX_Size() int {
	return xxx_messageInfo_StartReq.Size(m)
}
func (m *StartReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StartReq.DiscardUnknown(m)
}

var xxx_messageInfo_StartReq proto.InternalMessageInfo

func (m *StartReq) GetConfig() *JobConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

// StatusReq requests that the Agent send a status update message
// about the Job for this connection.
type StatusReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusReq) Reset()         { *m = StatusReq{} }
func (m *StatusReq) String() string { return proto.CompactTextString(m) }
func (*StatusReq) ProtoMessage()    {}
func (*StatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a60391ce6a1a9c17, []int{4}
}

func (m *StatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusReq.Unmarshal(m, b)
}
func (m *StatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusReq.Marshal(b, m, deterministic)
}
func (m *StatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusReq.Merge(m, src)
}
func (m *StatusReq) XXX_Size() int {
	return xxx_messageInfo_StatusReq.Size(m)
}
func (m *StatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_StatusReq proto.InternalMessageInfo

// StatusReport provides information about the Job for this connection.
// It should be issued promptly following receipt of a StartReq, StatusReq
// or CancelReq, and may be issued periodically otherwise at the Agent's
// discretion.
type StatusReport struct {
	// is the job running?
	RunStatus status.Status `protobuf:"varint,1,opt,name=runStatus,proto3,enum=status.Status" json:"runStatus,omitempty"`
	// is the job healthy?
	HealthStatus status.Health `protobuf:"varint,2,opt,name=healthStatus,proto3,enum=status.Health" json:"healthStatus,omitempty"`
	// time when the job was started, as Unix time
	TimeStarted int64 `protobuf:"varint,3,opt,name=timeStarted,proto3" json:"timeStarted,omitempty"`
	// time when the job stopped running, as Unix time
	TimeFinished int64 `protobuf:"varint,4,opt,name=timeFinished,proto3" json:"timeFinished,omitempty"`
	// logged output, if any. should be short messages; anything
	// lengthy should be separately logged or reported elsewhere
	OutputMessages       string   `protobuf:"bytes,5,opt,name=outputMessages,proto3" json:"outputMessages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusReport) Reset()         { *m = StatusReport{} }
func (m *StatusReport) String() string { return proto.CompactTextString(m) }
func (*StatusReport) ProtoMessage()    {}
func (*StatusReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_a60391ce6a1a9c17, []int{5}
}

func (m *StatusReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusReport.Unmarshal(m, b)
}
func (m *StatusReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusReport.Marshal(b, m, deterministic)
}
func (m *StatusReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusReport.Merge(m, src)
}
func (m *StatusReport) XXX_Size() int {
	return xxx_messageInfo_StatusReport.Size(m)
}
func (m *StatusReport) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusReport.DiscardUnknown(m)
}

var xxx_messageInfo_StatusReport proto.InternalMessageInfo

func (m *StatusReport) GetRunStatus() status.Status {
	if m != nil {
		return m.RunStatus
	}
	return status.Status_STATUS_SAME
}

func (m *StatusReport) GetHealthStatus() status.Health {
	if m != nil {
		return m.HealthStatus
	}
	return status.Health_HEALTH_SAME
}

func (m *StatusReport) GetTimeStarted() int64 {
	if m != nil {
		return m.TimeStarted
	}
	return 0
}

func (m *StatusReport) GetTimeFinished() int64 {
	if m != nil {
		return m.TimeFinished
	}
	return 0
}

func (m *StatusReport) GetOutputMessages() string {
	if m != nil {
		return m.OutputMessages
	}
	return ""
}

func init() {
	proto.RegisterType((*ControllerMsg)(nil), "agent.ControllerMsg")
	proto.RegisterType((*AgentMsg)(nil), "agent.AgentMsg")
	proto.RegisterType((*JobConfig)(nil), "agent.JobConfig")
	proto.RegisterType((*JobConfig_CodeInput)(nil), "agent.JobConfig.CodeInput")
	proto.RegisterType((*JobConfig_SpdxInput)(nil), "agent.JobConfig.SpdxInput")
	proto.RegisterType((*JobConfig_JobKV)(nil), "agent.JobConfig.JobKV")
	proto.RegisterType((*StartReq)(nil), "agent.StartReq")
	proto.RegisterType((*StatusReq)(nil), "agent.StatusReq")
	proto.RegisterType((*StatusReport)(nil), "agent.StatusReport")
}

func init() { proto.RegisterFile("pkg/agent/agent.proto", fileDescriptor_a60391ce6a1a9c17) }

var fileDescriptor_a60391ce6a1a9c17 = []byte{
	// 531 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x5f, 0x8f, 0xd2, 0x40,
	0x10, 0xc0, 0xaf, 0x57, 0x4a, 0xae, 0x03, 0x87, 0x64, 0x3d, 0x4f, 0xc2, 0x13, 0x69, 0x8c, 0x92,
	0x8b, 0x47, 0x15, 0x35, 0x26, 0x3e, 0x68, 0x3c, 0x8c, 0x39, 0x31, 0xa7, 0xc9, 0x92, 0xf8, 0xe0,
	0x5b, 0x0b, 0x6b, 0x5b, 0x28, 0xdd, 0xba, 0x7f, 0x0e, 0xfd, 0x32, 0x7e, 0x34, 0x3f, 0x8b, 0xd9,
	0xed, 0xb6, 0xb4, 0x18, 0x1f, 0x7c, 0x81, 0xce, 0xcc, 0x6f, 0xfe, 0x75, 0x66, 0x0a, 0xf7, 0xf2,
	0x4d, 0xe4, 0x07, 0x11, 0xc9, 0x44, 0xf1, 0x3b, 0xc9, 0x19, 0x15, 0x14, 0x39, 0x5a, 0x18, 0xde,
	0x57, 0x56, 0x2e, 0x02, 0x21, 0xb9, 0xf9, 0x2b, 0xec, 0xde, 0x1a, 0x4e, 0x67, 0x34, 0x13, 0x8c,
	0xa6, 0x29, 0x61, 0x37, 0x3c, 0x42, 0x8f, 0xc0, 0xe1, 0x22, 0x60, 0x62, 0x60, 0x8d, 0xac, 0x71,
	0x67, 0x7a, 0x67, 0x52, 0x44, 0x5b, 0x28, 0x1d, 0x26, 0xdf, 0xaf, 0x8f, 0x70, 0x61, 0x47, 0x17,
	0xd0, 0x2e, 0x22, 0x0d, 0x8e, 0x35, 0xd9, 0xdf, 0x93, 0x42, 0xf2, 0x02, 0x35, 0xc4, 0x55, 0x0b,
	0x8e, 0x97, 0x5b, 0xef, 0x0d, 0x9c, 0xbc, 0x55, 0x88, 0x4a, 0x73, 0x79, 0xe0, 0x7d, 0xf7, 0xc0,
	0x3b, 0xa7, 0x4c, 0x34, 0x03, 0x04, 0x5b, 0xef, 0x97, 0x0d, 0xee, 0x9c, 0x86, 0x33, 0x9a, 0x7d,
	0x4b, 0x22, 0xf4, 0x0a, 0x60, 0x49, 0x57, 0xe4, 0x43, 0x96, 0x4b, 0xc1, 0x07, 0xd6, 0xc8, 0x1e,
	0x77, 0xa6, 0x43, 0x13, 0xa6, 0xa2, 0x26, 0xb3, 0x12, 0xc1, 0x35, 0x1a, 0x3d, 0x80, 0x53, 0x25,
	0x7d, 0x96, 0x22, 0x97, 0xe2, 0x5d, 0xc2, 0x74, 0x15, 0x2e, 0x6e, 0x2a, 0x55, 0x06, 0x9e, 0xaf,
	0x7e, 0x98, 0x0c, 0xf6, 0x3f, 0x32, 0x2c, 0x4a, 0x04, 0xd7, 0x68, 0x95, 0x41, 0x49, 0xfb, 0x0c,
	0xad, 0x22, 0x43, 0x43, 0x89, 0x2e, 0xa0, 0xb5, 0xde, 0xdc, 0xf2, 0x81, 0xa3, 0x63, 0x9f, 0xff,
	0x15, 0x7b, 0x4e, 0xc3, 0x8f, 0x5f, 0xb0, 0x66, 0x86, 0x2f, 0xc1, 0xad, 0x9a, 0x41, 0xe7, 0xd0,
	0xe6, 0x54, 0xb2, 0x25, 0xd1, 0x73, 0x72, 0xb1, 0x91, 0x10, 0x82, 0x56, 0x1e, 0x88, 0xd8, 0xf4,
	0xa3, 0x9f, 0x95, 0x63, 0x55, 0xe3, 0x7f, 0x39, 0xfa, 0xe0, 0xe8, 0x02, 0x50, 0x1f, 0xec, 0x0d,
	0xf9, 0x69, 0x3c, 0xd4, 0x23, 0x3a, 0x03, 0xe7, 0x36, 0x48, 0x25, 0x31, 0x7c, 0x21, 0x78, 0xcf,
	0xe1, 0xa4, 0x5c, 0x14, 0x34, 0x86, 0xf6, 0x52, 0x37, 0x61, 0x36, 0xa9, 0x7f, 0xd8, 0x1c, 0x36,
	0x76, 0xaf, 0x03, 0x6e, 0xb5, 0x34, 0xde, 0x6f, 0x0b, 0xba, 0xf5, 0x25, 0x40, 0x8f, 0xc1, 0x65,
	0x32, 0x2b, 0x54, 0x3a, 0x54, 0x6f, 0xda, 0x9b, 0x98, 0x1d, 0x36, 0xe0, 0x1e, 0x40, 0x53, 0xe8,
	0xc6, 0x24, 0x48, 0x45, 0xbc, 0xd8, 0x6f, 0x57, 0xcd, 0xe1, 0x5a, 0xdb, 0x70, 0x83, 0x41, 0x23,
	0xe8, 0x88, 0x64, 0x4b, 0x74, 0xe5, 0x64, 0x35, 0xb0, 0x47, 0xd6, 0xd8, 0xc6, 0x75, 0x15, 0xf2,
	0xa0, 0xab, 0xc4, 0xf7, 0x49, 0x96, 0xf0, 0x98, 0xac, 0xf4, 0x2c, 0x6d, 0xdc, 0xd0, 0xa1, 0x87,
	0xd0, 0xa3, 0x7a, 0xae, 0x37, 0x84, 0xf3, 0x20, 0x22, 0x6a, 0xa8, 0xea, 0xd5, 0x1c, 0x68, 0xa7,
	0xaf, 0xc1, 0xd1, 0x57, 0x80, 0x5e, 0x40, 0xfb, 0x13, 0xd9, 0xcd, 0x69, 0x88, 0xce, 0xcc, 0xab,
	0x69, 0x5c, 0xe2, 0xb0, 0x3c, 0xbd, 0xf2, 0x66, 0xbc, 0xa3, 0xb1, 0xf5, 0xc4, 0xba, 0x7a, 0xfa,
	0xd5, 0x8f, 0x12, 0x11, 0xcb, 0x70, 0xb2, 0xa4, 0x5b, 0x9f, 0xef, 0x92, 0x8c, 0xa7, 0x74, 0xe7,
	0xe7, 0x84, 0x25, 0x2b, 0x2a, 0x2e, 0xd7, 0x34, 0x64, 0x32, 0xcb, 0x08, 0xf3, 0xab, 0x0f, 0x42,
	0xd8, 0xd6, 0xb7, 0xfe, 0xec, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xca, 0xd6, 0x02, 0xa6, 0x24,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentClient interface {
	// NewJob is the only RPC endpoint that an Agent provides. It
	// is a bidirectional streaming RPC that enables the Controller to
	// send messages to the Agent, and vice versa. It will remain open
	// during the lifetime of a given Job and its early termination
	// means that the Job should be treated as failed.
	NewJob(ctx context.Context, opts ...grpc.CallOption) (Agent_NewJobClient, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) NewJob(ctx context.Context, opts ...grpc.CallOption) (Agent_NewJobClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Agent_serviceDesc.Streams[0], "/agent.Agent/NewJob", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentNewJobClient{stream}
	return x, nil
}

type Agent_NewJobClient interface {
	Send(*ControllerMsg) error
	Recv() (*AgentMsg, error)
	grpc.ClientStream
}

type agentNewJobClient struct {
	grpc.ClientStream
}

func (x *agentNewJobClient) Send(m *ControllerMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentNewJobClient) Recv() (*AgentMsg, error) {
	m := new(AgentMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentServer is the server API for Agent service.
type AgentServer interface {
	// NewJob is the only RPC endpoint that an Agent provides. It
	// is a bidirectional streaming RPC that enables the Controller to
	// send messages to the Agent, and vice versa. It will remain open
	// during the lifetime of a given Job and its early termination
	// means that the Job should be treated as failed.
	NewJob(Agent_NewJobServer) error
}

// UnimplementedAgentServer can be embedded to have forward compatible implementations.
type UnimplementedAgentServer struct {
}

func (*UnimplementedAgentServer) NewJob(srv Agent_NewJobServer) error {
	return status1.Errorf(codes.Unimplemented, "method NewJob not implemented")
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_NewJob_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServer).NewJob(&agentNewJobServer{stream})
}

type Agent_NewJobServer interface {
	Send(*AgentMsg) error
	Recv() (*ControllerMsg, error)
	grpc.ServerStream
}

type agentNewJobServer struct {
	grpc.ServerStream
}

func (x *agentNewJobServer) Send(m *AgentMsg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *agentNewJobServer) Recv() (*ControllerMsg, error) {
	m := new(ControllerMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agent.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "NewJob",
			Handler:       _Agent_NewJob_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/agent/agent.proto",
}
